# Use an official Python runtime as a parent image
FROM python:3.10.6-slim

ARG TAG

# Install dependencies
RUN apt-get update -yqq && \
    apt-get install -yqq \
    make build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git tabix vcfanno \
    freebayes && \
    apt-get clean

# Install gsort
RUN \
    cd /usr/local/bin && \
    curl -s https://api.github.com/repos/brentp/gsort/releases/latest \
    | grep browser_download_url \
    | grep -i $(uname) \
    | cut -d '"' -f 4 \
    | wget -O gsort -qi - && \
    chmod +x gsort

RUN pip install pandas xlsxwriter pyfastx scipy pysam pyyaml
RUN pip install -i https://test.pypi.org/simple/ mitywgs==${TAG}

WORKDIR /home

ENTRYPOINT [ "mity" ]
