trigger:
  branches:
    include:
      - development

pr: none

resources:
  - repo: self

name: $(Date:yyyy).$(Date:MMdd)$(Rev:.r)
variables:
  packageName: "$(package-name)"
  tag: "$(Build.BuildNumber)"

  # Docker details
  dockerRegistryServiceConnection: "$(dockerhub-service-connection)"
  imageRepository: "$(image-repository)"
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile.dev" # docker file name

  # PyPi Details
  pypiServiceConnection: "$(pypi-service-connection)"

extends:
  template: pipeline-stages-template.yml
  parameters:
    packageName: "$(packageName)"
    tag: "$(tag)"
    dockerRegistryServiceConnection: "$(dockerRegistryServiceConnection)"
    imageRepository: "$(imageRepository)"
    dockerfilePath: "$(dockerfilePath)"
    pypiServiceConnection: "$(pypiServiceConnection)"
