#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Mity
    a sensitive variant analysis pipeline optimised for WGS data

Authors: Clare Puttick, Mark Cowley
License: MIT
"""

import logging
from mitylib import commands
from mitylib import util
import sys

assert sys.version_info >= (3, 7, 4)

if __name__ == '__main__':
    util.check_dependencies()

    args = commands.parse_args()

    debug_mode = args.debug

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    if debug_mode:
        print("Debug mode activated.")
        logging.basicConfig(level=logging.DEBUG, format="%(message)s")

    if len(vars(args)) == 0:
        logging.info("usage: mity -h")
    else:
        try:
            func = args.func
        except AttributeError:
            AP = commands.return_AP()
            AP.error("too few arguments")
        func(args)
